using BloodLineAPI.Model;
using System.Collections.Generic;
using System.Linq;

namespace BloodLineAPI.BAL
{
    public class DistrictBAL
    {
        public List<DistrictModel> GetAllDistricts()
        {
            return new List<DistrictModel>
            {
                // Andhra Pradesh (StateId = 1)
                new DistrictModel { DistrictId = 1, DistrictName = "Alluri Sitharama Raju", StateId = 1 },
                new DistrictModel { DistrictId = 2, DistrictName = "Anakapalli", StateId = 1 },
                new DistrictModel { DistrictId = 3, DistrictName = "Anantapuramu", StateId = 1 },
                new DistrictModel { DistrictId = 4, DistrictName = "Annamayya", StateId = 1 },
                new DistrictModel { DistrictId = 5, DistrictName = "Bapatla", StateId = 1 },
                new DistrictModel { DistrictId = 6, DistrictName = "Chittoor", StateId = 1 },
                new DistrictModel { DistrictId = 7, DistrictName = "Dr. B.R. Ambedkar Konaseema", StateId = 1 },
                new DistrictModel { DistrictId = 8, DistrictName = "East Godavari", StateId = 1 },
                new DistrictModel { DistrictId = 9, DistrictName = "Eluru", StateId = 1 },
                new DistrictModel { DistrictId = 10, DistrictName = "Guntur", StateId = 1 },
                new DistrictModel { DistrictId = 11, DistrictName = "Kakinada", StateId = 1 },
                new DistrictModel { DistrictId = 12, DistrictName = "Krishna", StateId = 1 },
                new DistrictModel { DistrictId = 13, DistrictName = "Kurnool", StateId = 1 },
                new DistrictModel { DistrictId = 14, DistrictName = "Nandyal", StateId = 1 },
                new DistrictModel { DistrictId = 15, DistrictName = "NTR", StateId = 1 },
                new DistrictModel { DistrictId = 16, DistrictName = "Palnadu", StateId = 1 },
                new DistrictModel { DistrictId = 17, DistrictName = "Parvathipuram Manyam", StateId = 1 },
                new DistrictModel { DistrictId = 18, DistrictName = "Prakasam", StateId = 1 },
                new DistrictModel { DistrictId = 19, DistrictName = "SR Nellore", StateId = 1 },
                new DistrictModel { DistrictId = 20, DistrictName = "Satya Sai", StateId = 1 },
                new DistrictModel { DistrictId = 21, DistrictName = "Srikakulam", StateId = 1 },
                new DistrictModel { DistrictId = 22, DistrictName = "Tirupati", StateId = 1 },
                new DistrictModel { DistrictId = 23, DistrictName = "Visakhapatnam", StateId = 1 },
                new DistrictModel { DistrictId = 24, DistrictName = "Vizianagaram", StateId = 1 },
                new DistrictModel { DistrictId = 25, DistrictName = "West Godavari", StateId = 1 },

                // Arunachal Pradesh (StateId = 2)
                new DistrictModel { DistrictId = 26, DistrictName = "Anjaw", StateId = 2 },
                new DistrictModel { DistrictId = 27, DistrictName = "Bichom", StateId = 2 },
                new DistrictModel { DistrictId = 28, DistrictName = "Changlang", StateId = 2 },
                new DistrictModel { DistrictId = 29, DistrictName = "Dibang Valley", StateId = 2 },
                new DistrictModel { DistrictId = 30, DistrictName = "East Kameng", StateId = 2 },
                new DistrictModel { DistrictId = 31, DistrictName = "East Siang", StateId = 2 },
                new DistrictModel { DistrictId = 32, DistrictName = "Kamle", StateId = 2 },
                new DistrictModel { DistrictId = 33, DistrictName = "Keyi Panyor", StateId = 2 },
                new DistrictModel { DistrictId = 34, DistrictName = "Kra Daadi", StateId = 2 },
                new DistrictModel { DistrictId = 35, DistrictName = "Kurung Kumey", StateId = 2 },
                new DistrictModel { DistrictId = 36, DistrictName = "Leparada", StateId = 2 },
                new DistrictModel { DistrictId = 37, DistrictName = "Lohit", StateId = 2 },
                new DistrictModel { DistrictId = 38, DistrictName = "Longding", StateId = 2 },
                new DistrictModel { DistrictId = 39, DistrictName = "Lower Dibang Valley", StateId = 2 },
                new DistrictModel { DistrictId = 40, DistrictName = "Lower Siang", StateId = 2 },
                new DistrictModel { DistrictId = 41, DistrictName = "Lower Subansiri", StateId = 2 },
                new DistrictModel { DistrictId = 42, DistrictName = "Namsai", StateId = 2 },
                new DistrictModel { DistrictId = 43, DistrictName = "Pakke Kessang", StateId = 2 },
                new DistrictModel { DistrictId = 44, DistrictName = "Papum Pare", StateId = 2 },
                new DistrictModel { DistrictId = 45, DistrictName = "Shi Yomi", StateId = 2 },
                new DistrictModel { DistrictId = 46, DistrictName = "Siang", StateId = 2 },
                new DistrictModel { DistrictId = 47, DistrictName = "Tawang", StateId = 2 },
                new DistrictModel { DistrictId = 48, DistrictName = "Tirap", StateId = 2 },
                new DistrictModel { DistrictId = 49, DistrictName = "Upper Siang", StateId = 2 },
                new DistrictModel { DistrictId = 50, DistrictName = "Upper Subansiri", StateId = 2 },
                new DistrictModel { DistrictId = 51, DistrictName = "Itanagar", StateId = 2 },
                new DistrictModel { DistrictId = 52, DistrictName = "West Kameng", StateId = 2 },
                new DistrictModel { DistrictId = 53, DistrictName = "West Siang", StateId = 2 },

                new DistrictModel { DistrictId = 54, DistrictName = "Baksa", StateId = 3 },
new DistrictModel { DistrictId = 55, DistrictName = "Bajali", StateId = 3 },
new DistrictModel { DistrictId = 56, DistrictName = "Barpeta", StateId = 3 },
new DistrictModel { DistrictId = 57, DistrictName = "Biswanath", StateId = 3 },
new DistrictModel { DistrictId = 58, DistrictName = "Bongaigaon", StateId = 3 },
new DistrictModel { DistrictId = 59, DistrictName = "Cachar", StateId = 3 },
new DistrictModel { DistrictId = 60, DistrictName = "Charaideo", StateId = 3 },
new DistrictModel { DistrictId = 61, DistrictName = "Chirang", StateId = 3 },
new DistrictModel { DistrictId = 62, DistrictName = "Darrang", StateId = 3 },
new DistrictModel { DistrictId = 63, DistrictName = "Dhemaji", StateId = 3 },
new DistrictModel { DistrictId = 64, DistrictName = "Dhubri", StateId = 3 },
new DistrictModel { DistrictId = 65, DistrictName = "Dibrugarh", StateId = 3 },
new DistrictModel { DistrictId = 66, DistrictName = "Dima Hasao", StateId = 3 },
new DistrictModel { DistrictId = 67, DistrictName = "Goalpara", StateId = 3 },
new DistrictModel { DistrictId = 68, DistrictName = "Golaghat", StateId = 3 },
new DistrictModel { DistrictId = 69, DistrictName = "Hailakandi", StateId = 3 },
new DistrictModel { DistrictId = 70, DistrictName = "Hojai", StateId = 3 },
new DistrictModel { DistrictId = 71, DistrictName = "Jorhat", StateId = 3 },
new DistrictModel { DistrictId = 72, DistrictName = "Kamrup Metropolitan", StateId = 3 },
new DistrictModel { DistrictId = 73, DistrictName = "Kamrup", StateId = 3 },
new DistrictModel { DistrictId = 74, DistrictName = "Karbi Anglong", StateId = 3 },
new DistrictModel { DistrictId = 75, DistrictName = "Karimganj", StateId = 3 },
new DistrictModel { DistrictId = 76, DistrictName = "Kokrajhar", StateId = 3 },
new DistrictModel { DistrictId = 77, DistrictName = "Lakhimpur", StateId = 3 },
new DistrictModel { DistrictId = 78, DistrictName = "Majuli", StateId = 3 },
new DistrictModel { DistrictId = 79, DistrictName = "Morigaon", StateId = 3 },
new DistrictModel { DistrictId = 80, DistrictName = "Nagaon", StateId = 3 },
new DistrictModel { DistrictId = 81, DistrictName = "Nalbari", StateId = 3 },
new DistrictModel { DistrictId = 82, DistrictName = "Sivasagar", StateId = 3 },
new DistrictModel { DistrictId = 83, DistrictName = "Sonitpur", StateId = 3 },
new DistrictModel { DistrictId = 84, DistrictName = "South Salmara-Mankachar", StateId = 3 },
new DistrictModel { DistrictId = 85, DistrictName = "Tamulpur", StateId = 3 },
new DistrictModel { DistrictId = 86, DistrictName = "Tinsukia", StateId = 3 },
new DistrictModel { DistrictId = 87, DistrictName = "Udalguri", StateId = 3 },
new DistrictModel { DistrictId = 88, DistrictName = "West Karbi Anglong", StateId = 3 },

// Bihar (StateId = 4)
new DistrictModel { DistrictId = 89, DistrictName = "Araria", StateId = 4 },
new DistrictModel { DistrictId = 90, DistrictName = "Arwal", StateId = 4 },
new DistrictModel { DistrictId = 91, DistrictName = "Aurangabad", StateId = 4 },
new DistrictModel { DistrictId = 92, DistrictName = "Banka", StateId = 4 },
new DistrictModel { DistrictId = 93, DistrictName = "Begusarai", StateId = 4 },
new DistrictModel { DistrictId = 94, DistrictName = "Bhagalpur", StateId = 4 },
new DistrictModel { DistrictId = 95, DistrictName = "Bhojpur", StateId = 4 },
new DistrictModel { DistrictId = 96, DistrictName = "Buxar", StateId = 4 },
new DistrictModel { DistrictId = 97, DistrictName = "Darbhanga", StateId = 4 },
new DistrictModel { DistrictId = 98, DistrictName = "East Champaran", StateId = 4 },
new DistrictModel { DistrictId = 99, DistrictName = "Gaya", StateId = 4 },
new DistrictModel { DistrictId = 100, DistrictName = "Gopalganj", StateId = 4 },
new DistrictModel { DistrictId = 101, DistrictName = "Jamui", StateId = 4 },
new DistrictModel { DistrictId = 102, DistrictName = "Jehanabad", StateId = 4 },
new DistrictModel { DistrictId = 103, DistrictName = "Kaimur (Bhabua)", StateId = 4 },
new DistrictModel { DistrictId = 104, DistrictName = "Katihar", StateId = 4 },
new DistrictModel { DistrictId = 105, DistrictName = "Khagaria", StateId = 4 },
new DistrictModel { DistrictId = 106, DistrictName = "Kishanganj", StateId = 4 },
new DistrictModel { DistrictId = 107, DistrictName = "Lakhisarai", StateId = 4 },
new DistrictModel { DistrictId = 108, DistrictName = "Madhepura", StateId = 4 },
new DistrictModel { DistrictId = 109, DistrictName = "Madhubani", StateId = 4 },
new DistrictModel { DistrictId = 110, DistrictName = "Munger", StateId = 4 },
new DistrictModel { DistrictId = 111, DistrictName = "Muzaffarpur", StateId = 4 },
new DistrictModel { DistrictId = 112, DistrictName = "Nalanda", StateId = 4 },
new DistrictModel { DistrictId = 113, DistrictName = "Nawada", StateId = 4 },
new DistrictModel { DistrictId = 114, DistrictName = "Patna", StateId = 4 },
new DistrictModel { DistrictId = 115, DistrictName = "Purnia", StateId = 4 },
new DistrictModel { DistrictId = 116, DistrictName = "Rohtas", StateId = 4 },
new DistrictModel { DistrictId = 117, DistrictName = "Saharsa", StateId = 4 },
new DistrictModel { DistrictId = 118, DistrictName = "Samastipur", StateId = 4 },
new DistrictModel { DistrictId = 119, DistrictName = "Saran", StateId = 4 },
new DistrictModel { DistrictId = 120, DistrictName = "Sheikhpura", StateId = 4 },
new DistrictModel { DistrictId = 121, DistrictName = "Sheohar", StateId = 4 },
new DistrictModel { DistrictId = 122, DistrictName = "Sitamarhi", StateId = 4 },
new DistrictModel { DistrictId = 123, DistrictName = "Siwan", StateId = 4 },
new DistrictModel { DistrictId = 124, DistrictName = "Supaul", StateId = 4 },
new DistrictModel { DistrictId = 125, DistrictName = "Vaishali", StateId = 4 },
new DistrictModel { DistrictId = 126, DistrictName = "West Champaran", StateId = 4 },

// Chhattisgarh (StateId = 5)
new DistrictModel { DistrictId = 127, DistrictName = "Balod", StateId = 5 },
new DistrictModel { DistrictId = 128, DistrictName = "Balodabazar-Bhatapara", StateId = 5 },
new DistrictModel { DistrictId = 129, DistrictName = "Balrampur", StateId = 5 },
new DistrictModel { DistrictId = 130, DistrictName = "Bastar", StateId = 5 },
new DistrictModel { DistrictId = 131, DistrictName = "Bemetara", StateId = 5 },
new DistrictModel { DistrictId = 132, DistrictName = "Bijapur", StateId = 5 },
new DistrictModel { DistrictId = 133, DistrictName = "Bilaspur", StateId = 5 },
new DistrictModel { DistrictId = 134, DistrictName = "Dantewada", StateId = 5 },
new DistrictModel { DistrictId = 135, DistrictName = "Dhamtari", StateId = 5 },
new DistrictModel { DistrictId = 136, DistrictName = "Durg", StateId = 5 },
new DistrictModel { DistrictId = 137, DistrictName = "Gariaband", StateId = 5 },
new DistrictModel { DistrictId = 138, DistrictName = "Gaurela-Pendra-Marwahi", StateId = 5 },
new DistrictModel { DistrictId = 139, DistrictName = "Janjgir-Champa", StateId = 5 },
new DistrictModel { DistrictId = 140, DistrictName = "Jashpur", StateId = 5 },
new DistrictModel { DistrictId = 141, DistrictName = "Kanker", StateId = 5 },
new DistrictModel { DistrictId = 142, DistrictName = "Kabirdham (Kawardha)", StateId = 5 },
new DistrictModel { DistrictId = 143, DistrictName = "Khairagarh-Chhuikhadan-Gandai", StateId = 5 },
new DistrictModel { DistrictId = 144, DistrictName = "Kondagaon", StateId = 5 },
new DistrictModel { DistrictId = 145, DistrictName = "Korba", StateId = 5 },
new DistrictModel { DistrictId = 146, DistrictName = "Koriya", StateId = 5 },
new DistrictModel { DistrictId = 147, DistrictName = "Mahasamund", StateId = 5 },
new DistrictModel { DistrictId = 148, DistrictName = "Manendragarh-Chirmiri-Bharatpur", StateId = 5 },
new DistrictModel { DistrictId = 149, DistrictName = "Mohla-Manpur-Ambagarh Chowki", StateId = 5 },
new DistrictModel { DistrictId = 150, DistrictName = "Mungeli", StateId = 5 },
new DistrictModel { DistrictId = 151, DistrictName = "Narayanpur", StateId = 5 },
new DistrictModel { DistrictId = 152, DistrictName = "Raigarh", StateId = 5 },
new DistrictModel { DistrictId = 153, DistrictName = "Raipur", StateId = 5 },
new DistrictModel { DistrictId = 154, DistrictName = "Rajnandgaon", StateId = 5 },
new DistrictModel { DistrictId = 155, DistrictName = "Sarangarh-Bilaigarh", StateId = 5 },
new DistrictModel { DistrictId = 156, DistrictName = "Sakti", StateId = 5 },
new DistrictModel { DistrictId = 157, DistrictName = "Sukma", StateId = 5 },
new DistrictModel { DistrictId = 158, DistrictName = "Surajpur", StateId = 5 },
new DistrictModel { DistrictId = 159, DistrictName = "Surguja", StateId = 5 },

// Goa (StateId = 6)
new DistrictModel { DistrictId = 160, DistrictName = "North Goa", StateId = 6 },
new DistrictModel { DistrictId = 161, DistrictName = "South Goa", StateId = 6 },

// Gujarat (StateId = 7)
new DistrictModel { DistrictId = 162, DistrictName = "Ahmedabad", StateId = 7 },
new DistrictModel { DistrictId = 163, DistrictName = "Amreli", StateId = 7 },
new DistrictModel { DistrictId = 164, DistrictName = "Anand", StateId = 7 },
new DistrictModel { DistrictId = 165, DistrictName = "Aravalli", StateId = 7 },
new DistrictModel { DistrictId = 166, DistrictName = "Banaskantha", StateId = 7 },
new DistrictModel { DistrictId = 167, DistrictName = "Bharuch", StateId = 7 },
new DistrictModel { DistrictId = 168, DistrictName = "Bhavnagar", StateId = 7 },
new DistrictModel { DistrictId = 169, DistrictName = "Botad", StateId = 7 },
new DistrictModel { DistrictId = 170, DistrictName = "Chhota Udaipur", StateId = 7 },
new DistrictModel { DistrictId = 171, DistrictName = "Dahod", StateId = 7 },
new DistrictModel { DistrictId = 172, DistrictName = "Dang", StateId = 7 },
new DistrictModel { DistrictId = 173, DistrictName = "Devbhoomi Dwarka", StateId = 7 },
new DistrictModel { DistrictId = 174, DistrictName = "Gandhinagar", StateId = 7 },
new DistrictModel { DistrictId = 175, DistrictName = "Gir Somnath", StateId = 7 },
new DistrictModel { DistrictId = 176, DistrictName = "Jamnagar", StateId = 7 },
new DistrictModel { DistrictId = 177, DistrictName = "Junagadh", StateId = 7 },
new DistrictModel { DistrictId = 178, DistrictName = "Kheda", StateId = 7 },
new DistrictModel { DistrictId = 179, DistrictName = "Kutch", StateId = 7 },
new DistrictModel { DistrictId = 180, DistrictName = "Mahisagar", StateId = 7 },
new DistrictModel { DistrictId = 181, DistrictName = "Mehsana", StateId = 7 },
new DistrictModel { DistrictId = 182, DistrictName = "Morbi", StateId = 7 },
new DistrictModel { DistrictId = 183, DistrictName = "Narmada", StateId = 7 },
new DistrictModel { DistrictId = 184, DistrictName = "Navsari", StateId = 7 },
new DistrictModel { DistrictId = 185, DistrictName = "Panchmahal", StateId = 7 },
new DistrictModel { DistrictId = 186, DistrictName = "Patan", StateId = 7 },
new DistrictModel { DistrictId = 187, DistrictName = "Porbandar", StateId = 7 },
new DistrictModel { DistrictId = 188, DistrictName = "Rajkot", StateId = 7 },
new DistrictModel { DistrictId = 189, DistrictName = "Sabarkantha", StateId = 7 },
new DistrictModel { DistrictId = 190, DistrictName = "Surat", StateId = 7 },
new DistrictModel { DistrictId = 191, DistrictName = "Surendranagar", StateId = 7 },
new DistrictModel { DistrictId = 192, DistrictName = "Tapi", StateId = 7 },
new DistrictModel { DistrictId = 193, DistrictName = "Vadodara", StateId = 7 },
new DistrictModel { DistrictId = 194, DistrictName = "Valsad", StateId = 7 },

// Haryana (StateId = 8)
new DistrictModel { DistrictId = 195, DistrictName = "Ambala", StateId = 8 },
new DistrictModel { DistrictId = 196, DistrictName = "Bhiwani", StateId = 8 },
new DistrictModel { DistrictId = 197, DistrictName = "Charkhi Dadri", StateId = 8 },
new DistrictModel { DistrictId = 198, DistrictName = "Faridabad", StateId = 8 },
new DistrictModel { DistrictId = 199, DistrictName = "Fatehabad", StateId = 8 },
new DistrictModel { DistrictId = 200, DistrictName = "Gurugram", StateId = 8 },
new DistrictModel { DistrictId = 201, DistrictName = "Hisar", StateId = 8 },
new DistrictModel { DistrictId = 202, DistrictName = "Jhajjar", StateId = 8 },
new DistrictModel { DistrictId = 203, DistrictName = "Jind", StateId = 8 },
new DistrictModel { DistrictId = 204, DistrictName = "Kaithal", StateId = 8 },
new DistrictModel { DistrictId = 205, DistrictName = "Karnal", StateId = 8 },
new DistrictModel { DistrictId = 206, DistrictName = "Kurukshetra", StateId = 8 },
new DistrictModel { DistrictId = 207, DistrictName = "Mahendragarh", StateId = 8 },
new DistrictModel { DistrictId = 208, DistrictName = "Nuh", StateId = 8 },
new DistrictModel { DistrictId = 209, DistrictName = "Palwal", StateId = 8 },
new DistrictModel { DistrictId = 210, DistrictName = "Panchkula", StateId = 8 },
new DistrictModel { DistrictId = 211, DistrictName = "Panipat", StateId = 8 },
new DistrictModel { DistrictId = 212, DistrictName = "Rewari", StateId = 8 },
new DistrictModel { DistrictId = 213, DistrictName = "Rohtak", StateId = 8 },
new DistrictModel { DistrictId = 214, DistrictName = "Sirsa", StateId = 8 },
new DistrictModel { DistrictId = 215, DistrictName = "Sonipat", StateId = 8 },
new DistrictModel { DistrictId = 216, DistrictName = "Yamunanagar", StateId = 8 },

new DistrictModel { DistrictId = 217, DistrictName = "Bilaspur", StateId = 9 },
new DistrictModel { DistrictId = 218, DistrictName = "Chamba", StateId = 9 },
new DistrictModel { DistrictId = 219, DistrictName = "Hamirpur", StateId = 9 },
new DistrictModel { DistrictId = 220, DistrictName = "Kangra", StateId = 9 },
new DistrictModel { DistrictId = 221, DistrictName = "Kinnaur", StateId = 9 },
new DistrictModel { DistrictId = 222, DistrictName = "Kullu", StateId = 9 },
new DistrictModel { DistrictId = 223, DistrictName = "Lahaul and Spiti", StateId = 9 },
new DistrictModel { DistrictId = 224, DistrictName = "Mandi", StateId = 9 },
new DistrictModel { DistrictId = 225, DistrictName = "Shimla", StateId = 9 },
new DistrictModel { DistrictId = 226, DistrictName = "Sirmaur", StateId = 9 },
new DistrictModel { DistrictId = 227, DistrictName = "Solan", StateId = 9 },
new DistrictModel { DistrictId = 228, DistrictName = "Una", StateId = 9 },

new DistrictModel { DistrictId = 229, DistrictName = "Bokaro", StateId = 10 },
new DistrictModel { DistrictId = 230, DistrictName = "Chatra", StateId = 10 },
new DistrictModel { DistrictId = 231, DistrictName = "Deoghar", StateId = 10 },
new DistrictModel { DistrictId = 232, DistrictName = "Dhanbad", StateId = 10 },
new DistrictModel { DistrictId = 233, DistrictName = "Dumka", StateId = 10 },
new DistrictModel { DistrictId = 234, DistrictName = "East Singhbhum", StateId = 10 },
new DistrictModel { DistrictId = 235, DistrictName = "Garhwa", StateId = 10 },
new DistrictModel { DistrictId = 236, DistrictName = "Giridih", StateId = 10 },
new DistrictModel { DistrictId = 237, DistrictName = "Godda", StateId = 10 },
new DistrictModel { DistrictId = 238, DistrictName = "Gumla", StateId = 10 },
new DistrictModel { DistrictId = 239, DistrictName = "Hazaribagh", StateId = 10 },
new DistrictModel { DistrictId = 240, DistrictName = "Jamtara", StateId = 10 },
new DistrictModel { DistrictId = 241, DistrictName = "Khunti", StateId = 10 },
new DistrictModel { DistrictId = 242, DistrictName = "Koderma", StateId = 10 },
new DistrictModel { DistrictId = 243, DistrictName = "Latehar", StateId = 10 },
new DistrictModel { DistrictId = 244, DistrictName = "Lohardaga", StateId = 10 },
new DistrictModel { DistrictId = 245, DistrictName = "Pakur", StateId = 10 },
new DistrictModel { DistrictId = 246, DistrictName = "Palamu", StateId = 10 },
new DistrictModel { DistrictId = 247, DistrictName = "Ramgarh", StateId = 10 },
new DistrictModel { DistrictId = 248, DistrictName = "Ranchi", StateId = 10 },
new DistrictModel { DistrictId = 249, DistrictName = "Sahibganj", StateId = 10 },
new DistrictModel { DistrictId = 250, DistrictName = "Seraikela Kharsawan", StateId = 10 },
new DistrictModel { DistrictId = 251, DistrictName = "Simdega", StateId = 10 },
new DistrictModel { DistrictId = 252, DistrictName = "West Singhbhum", StateId = 10 },

new DistrictModel { DistrictId = 253, DistrictName = "Bagalkot", StateId = 11 },
new DistrictModel { DistrictId = 254, DistrictName = "Ballari", StateId = 11 },
new DistrictModel { DistrictId = 255, DistrictName = "Belagavi", StateId = 11 },
new DistrictModel { DistrictId = 256, DistrictName = "Bengaluru Rural", StateId = 11 },
new DistrictModel { DistrictId = 257, DistrictName = "Bengaluru Urban", StateId = 11 },
new DistrictModel { DistrictId = 258, DistrictName = "Bidar", StateId = 11 },
new DistrictModel { DistrictId = 259, DistrictName = "Chamarajanagar", StateId = 11 },
new DistrictModel { DistrictId = 260, DistrictName = "Chikkaballapur", StateId = 11 },
new DistrictModel { DistrictId = 261, DistrictName = "Chikkamagaluru", StateId = 11 },
new DistrictModel { DistrictId = 262, DistrictName = "Chitradurga", StateId = 11 },
new DistrictModel { DistrictId = 263, DistrictName = "Dakshina Kannada", StateId = 11 },
new DistrictModel { DistrictId = 264, DistrictName = "Davanagere", StateId = 11 },
new DistrictModel { DistrictId = 265, DistrictName = "Dharwad", StateId = 11 },
new DistrictModel { DistrictId = 266, DistrictName = "Gadag", StateId = 11 },
new DistrictModel { DistrictId = 267, DistrictName = "Hassan", StateId = 11 },
new DistrictModel { DistrictId = 268, DistrictName = "Haveri", StateId = 11 },
new DistrictModel { DistrictId = 269, DistrictName = "Kalaburagi", StateId = 11 },
new DistrictModel { DistrictId = 270, DistrictName = "Kodagu", StateId = 11 },
new DistrictModel { DistrictId = 271, DistrictName = "Kolar", StateId = 11 },
new DistrictModel { DistrictId = 272, DistrictName = "Koppal", StateId = 11 },
new DistrictModel { DistrictId = 273, DistrictName = "Mandya", StateId = 11 },
new DistrictModel { DistrictId = 274, DistrictName = "Mysuru", StateId = 11 },
new DistrictModel { DistrictId = 275, DistrictName = "Raichur", StateId = 11 },
new DistrictModel { DistrictId = 276, DistrictName = "Ramanagara", StateId = 11 },
new DistrictModel { DistrictId = 277, DistrictName = "Shivamogga", StateId = 11 },
new DistrictModel { DistrictId = 278, DistrictName = "Tumakuru", StateId = 11 },
new DistrictModel { DistrictId = 279, DistrictName = "Udupi", StateId = 11 },
new DistrictModel { DistrictId = 280, DistrictName = "Uttara Kannada", StateId = 11 },
new DistrictModel { DistrictId = 281, DistrictName = "Vijayanagara", StateId = 11 },
new DistrictModel { DistrictId = 282, DistrictName = "Vijayapura", StateId = 11 },
new DistrictModel { DistrictId = 283, DistrictName = "Yadgir", StateId = 11 },

new DistrictModel { DistrictId = 284, DistrictName = "Alappuzha", StateId = 12 },
new DistrictModel { DistrictId = 285, DistrictName = "Ernakulam", StateId = 12 },
new DistrictModel { DistrictId = 286, DistrictName = "Idukki", StateId = 12 },
new DistrictModel { DistrictId = 287, DistrictName = "Kannur", StateId = 12 },
new DistrictModel { DistrictId = 288, DistrictName = "Kasaragod", StateId = 12 },
new DistrictModel { DistrictId = 289, DistrictName = "Kollam", StateId = 12 },
new DistrictModel { DistrictId = 290, DistrictName = "Kottayam", StateId = 12 },
new DistrictModel { DistrictId = 291, DistrictName = "Kozhikode", StateId = 12 },
new DistrictModel { DistrictId = 292, DistrictName = "Malappuram", StateId = 12 },
new DistrictModel { DistrictId = 293, DistrictName = "Palakkad", StateId = 12 },
new DistrictModel { DistrictId = 294, DistrictName = "Pathanamthitta", StateId = 12 },
new DistrictModel { DistrictId = 295, DistrictName = "Thiruvananthapuram", StateId = 12 },
new DistrictModel { DistrictId = 296, DistrictName = "Thrissur", StateId = 12 },
new DistrictModel { DistrictId = 297, DistrictName = "Wayanad", StateId = 12 },

// Districts for Madhya Pradesh (StateId = 13)
new DistrictModel { DistrictId = 298, DistrictName = "Agar Malwa", StateId = 13 },
new DistrictModel { DistrictId = 299, DistrictName = "Alirajpur", StateId = 13 },
new DistrictModel { DistrictId = 300, DistrictName = "Anuppur", StateId = 13 },
new DistrictModel { DistrictId = 301, DistrictName = "Ashoknagar", StateId = 13 },
new DistrictModel { DistrictId = 302, DistrictName = "Balaghat", StateId = 13 },
new DistrictModel { DistrictId = 303, DistrictName = "Barwani", StateId = 13 },
new DistrictModel { DistrictId = 304, DistrictName = "Betul", StateId = 13 },
new DistrictModel { DistrictId = 305, DistrictName = "Bhind", StateId = 13 },
new DistrictModel { DistrictId = 306, DistrictName = "Bhopal", StateId = 13 },
new DistrictModel { DistrictId = 307, DistrictName = "Burhanpur", StateId = 13 },
new DistrictModel { DistrictId = 308, DistrictName = "Chhatarpur", StateId = 13 },
new DistrictModel { DistrictId = 309, DistrictName = "Chhindwara", StateId = 13 },
new DistrictModel { DistrictId = 310, DistrictName = "Damoh", StateId = 13 },
new DistrictModel { DistrictId = 311, DistrictName = "Datia", StateId = 13 },
new DistrictModel { DistrictId = 312, DistrictName = "Dewas", StateId = 13 },
new DistrictModel { DistrictId = 313, DistrictName = "Dhar", StateId = 13 },
new DistrictModel { DistrictId = 314, DistrictName = "Dindori", StateId = 13 },
new DistrictModel { DistrictId = 315, DistrictName = "Guna", StateId = 13 },
new DistrictModel { DistrictId = 316, DistrictName = "Gwalior", StateId = 13 },
new DistrictModel { DistrictId = 317, DistrictName = "Harda", StateId = 13 },
new DistrictModel { DistrictId = 318, DistrictName = "Hoshangabad", StateId = 13 },
new DistrictModel { DistrictId = 319, DistrictName = "Indore", StateId = 13 },
new DistrictModel { DistrictId = 320, DistrictName = "Jabalpur", StateId = 13 },
new DistrictModel { DistrictId = 321, DistrictName = "Jhabua", StateId = 13 },
new DistrictModel { DistrictId = 322, DistrictName = "Katni", StateId = 13 },
new DistrictModel { DistrictId = 323, DistrictName = "Khandwa", StateId = 13 },
new DistrictModel { DistrictId = 324, DistrictName = "Khargone", StateId = 13 },
new DistrictModel { DistrictId = 325, DistrictName = "Mandla", StateId = 13 },
new DistrictModel { DistrictId = 326, DistrictName = "Mandsaur", StateId = 13 },
new DistrictModel { DistrictId = 327, DistrictName = "Morena", StateId = 13 },
new DistrictModel { DistrictId = 328, DistrictName = "Narsinghpur", StateId = 13 },
new DistrictModel { DistrictId = 329, DistrictName = "Neemuch", StateId = 13 },
new DistrictModel { DistrictId = 330, DistrictName = "Niwari", StateId = 13 },
new DistrictModel { DistrictId = 331, DistrictName = "Panna", StateId = 13 },
new DistrictModel { DistrictId = 332, DistrictName = "Raisen", StateId = 13 },
new DistrictModel { DistrictId = 333, DistrictName = "Rajgarh", StateId = 13 },
new DistrictModel { DistrictId = 334, DistrictName = "Ratlam", StateId = 13 },
new DistrictModel { DistrictId = 335, DistrictName = "Rewa", StateId = 13 },
new DistrictModel { DistrictId = 336, DistrictName = "Sagar", StateId = 13 },
new DistrictModel { DistrictId = 337, DistrictName = "Satna", StateId = 13 },
new DistrictModel { DistrictId = 338, DistrictName = "Sehore", StateId = 13 },
new DistrictModel { DistrictId = 339, DistrictName = "Seoni", StateId = 13 },
new DistrictModel { DistrictId = 340, DistrictName = "Shahdol", StateId = 13 },
new DistrictModel { DistrictId = 341, DistrictName = "Shajapur", StateId = 13 },
new DistrictModel { DistrictId = 342, DistrictName = "Sheopur", StateId = 13 },
new DistrictModel { DistrictId = 343, DistrictName = "Shivpuri", StateId = 13 },
new DistrictModel { DistrictId = 344, DistrictName = "Sidhi", StateId = 13 },
new DistrictModel { DistrictId = 345, DistrictName = "Singrauli", StateId = 13 },
new DistrictModel { DistrictId = 346, DistrictName = "Tikamgarh", StateId = 13 },
new DistrictModel { DistrictId = 347, DistrictName = "Ujjain", StateId = 13 },
new DistrictModel { DistrictId = 348, DistrictName = "Umaria", StateId = 13 },
new DistrictModel { DistrictId = 349, DistrictName = "Vidisha", StateId = 13 },

// Districts for Maharashtra (StateId = 14)
new DistrictModel { DistrictId = 350, DistrictName = "Ahmednagar", StateId = 14 },
new DistrictModel { DistrictId = 351, DistrictName = "Akola", StateId = 14 },
new DistrictModel { DistrictId = 352, DistrictName = "Amravati", StateId = 14 },
new DistrictModel { DistrictId = 353, DistrictName = "Aurangabad", StateId = 14 },
new DistrictModel { DistrictId = 354, DistrictName = "Beed", StateId = 14 },
new DistrictModel { DistrictId = 355, DistrictName = "Bhandara", StateId = 14 },
new DistrictModel { DistrictId = 356, DistrictName = "Buldhana", StateId = 14 },
new DistrictModel { DistrictId = 357, DistrictName = "Chandrapur", StateId = 14 },
new DistrictModel { DistrictId = 358, DistrictName = "Dhule", StateId = 14 },
new DistrictModel { DistrictId = 359, DistrictName = "Gadchiroli", StateId = 14 },
new DistrictModel { DistrictId = 360, DistrictName = "Gondia", StateId = 14 },
new DistrictModel { DistrictId = 361, DistrictName = "Hingoli", StateId = 14 },
new DistrictModel { DistrictId = 362, DistrictName = "Jalgaon", StateId = 14 },
new DistrictModel { DistrictId = 363, DistrictName = "Jalna", StateId = 14 },
new DistrictModel { DistrictId = 364, DistrictName = "Kolhapur", StateId = 14 },
new DistrictModel { DistrictId = 365, DistrictName = "Latur", StateId = 14 },
new DistrictModel { DistrictId = 366, DistrictName = "Mumbai City", StateId = 14 },
new DistrictModel { DistrictId = 367, DistrictName = "Mumbai Suburban", StateId = 14 },
new DistrictModel { DistrictId = 368, DistrictName = "Nagpur", StateId = 14 },
new DistrictModel { DistrictId = 369, DistrictName = "Nanded", StateId = 14 },
new DistrictModel { DistrictId = 370, DistrictName = "Nandurbar", StateId = 14 },
new DistrictModel { DistrictId = 371, DistrictName = "Nashik", StateId = 14 },
new DistrictModel { DistrictId = 372, DistrictName = "Osmanabad", StateId = 14 },
new DistrictModel { DistrictId = 373, DistrictName = "Palghar", StateId = 14 },
new DistrictModel { DistrictId = 374, DistrictName = "Parbhani", StateId = 14 },
new DistrictModel { DistrictId = 375, DistrictName = "Pune", StateId = 14 },
new DistrictModel { DistrictId = 376, DistrictName = "Raigad", StateId = 14 },
new DistrictModel { DistrictId = 377, DistrictName = "Ratnagiri", StateId = 14 },
new DistrictModel { DistrictId = 378, DistrictName = "Sangli", StateId = 14 },
new DistrictModel { DistrictId = 379, DistrictName = "Satara", StateId = 14 },
new DistrictModel { DistrictId = 380, DistrictName = "Sindhudurg", StateId = 14 },
new DistrictModel { DistrictId = 381, DistrictName = "Solapur", StateId = 14 },
new DistrictModel { DistrictId = 382, DistrictName = "Thane", StateId = 14 },
new DistrictModel { DistrictId = 383, DistrictName = "Wardha", StateId = 14 },
new DistrictModel { DistrictId = 384, DistrictName = "Washim", StateId = 14 },
new DistrictModel { DistrictId = 385, DistrictName = "Yavatmal", StateId = 14 },

// Districts for Manipur (StateId = 15)
new DistrictModel { DistrictId = 386, DistrictName = "Bishnupur", StateId = 15 },
new DistrictModel { DistrictId = 387, DistrictName = "Chandel", StateId = 15 },
new DistrictModel { DistrictId = 388, DistrictName = "Churachandpur", StateId = 15 },
new DistrictModel { DistrictId = 389, DistrictName = "Imphal East", StateId = 15 },
new DistrictModel { DistrictId = 390, DistrictName = "Imphal West", StateId = 15 },
new DistrictModel { DistrictId = 391, DistrictName = "Jiribam", StateId = 15 },
new DistrictModel { DistrictId = 392, DistrictName = "Kakching", StateId = 15 },
new DistrictModel { DistrictId = 393, DistrictName = "Kamjong", StateId = 15 },
new DistrictModel { DistrictId = 394, DistrictName = "Kangpokpi", StateId = 15 },
new DistrictModel { DistrictId = 395, DistrictName = "Noney", StateId = 15 },
new DistrictModel { DistrictId = 396, DistrictName = "Pherzawl", StateId = 15 },
new DistrictModel { DistrictId = 397, DistrictName = "Senapati", StateId = 15 },
new DistrictModel { DistrictId = 398, DistrictName = "Tamenglong", StateId = 15 },
new DistrictModel { DistrictId = 399, DistrictName = "Tengnoupal", StateId = 15 },
new DistrictModel { DistrictId = 400, DistrictName = "Thoubal", StateId = 15 },
new DistrictModel { DistrictId = 401, DistrictName = "Ukhrul", StateId = 15 },

// Districts for Meghalaya (StateId = 16)
new DistrictModel { DistrictId = 402, DistrictName = "East Garo Hills", StateId = 16 },
new DistrictModel { DistrictId = 403, DistrictName = "East Jaintia Hills", StateId = 16 },
new DistrictModel { DistrictId = 404, DistrictName = "East Khasi Hills", StateId = 16 },
new DistrictModel { DistrictId = 405, DistrictName = "North Garo Hills", StateId = 16 },
new DistrictModel { DistrictId = 406, DistrictName = "Ri-Bhoi", StateId = 16 },
new DistrictModel { DistrictId = 407, DistrictName = "South Garo Hills", StateId = 16 },
new DistrictModel { DistrictId = 408, DistrictName = "South West Garo Hills", StateId = 16 },
new DistrictModel { DistrictId = 409, DistrictName = "South West Khasi Hills", StateId = 16 },
new DistrictModel { DistrictId = 410, DistrictName = "West Garo Hills", StateId = 16 },
new DistrictModel { DistrictId = 411, DistrictName = "West Jaintia Hills", StateId = 16 },
new DistrictModel { DistrictId = 412, DistrictName = "West Khasi Hills", StateId = 16 },

new DistrictModel { DistrictId = 413, DistrictName = "Aizawl", StateId = 17 },
new DistrictModel { DistrictId = 414, DistrictName = "Champhai", StateId = 17 },
new DistrictModel { DistrictId = 415, DistrictName = "Hnahthial", StateId = 17 },
new DistrictModel { DistrictId = 416, DistrictName = "Khawzawl", StateId = 17 },
new DistrictModel { DistrictId = 417, DistrictName = "Kolasib", StateId = 17 },
new DistrictModel { DistrictId = 418, DistrictName = "Lawngtlai", StateId = 17 },
new DistrictModel { DistrictId = 419, DistrictName = "Lunglei", StateId = 17 },
new DistrictModel { DistrictId = 420, DistrictName = "Mamit", StateId = 17 },
new DistrictModel { DistrictId = 421, DistrictName = "Saiha", StateId = 17 },
new DistrictModel { DistrictId = 422, DistrictName = "Saitual", StateId = 17 },
new DistrictModel { DistrictId = 423, DistrictName = "Serchhip", StateId = 17 },

new DistrictModel { DistrictId = 424, DistrictName = "Chümoukedima", StateId = 18 },
new DistrictModel { DistrictId = 425, DistrictName = "Dimapur", StateId = 18 },
new DistrictModel { DistrictId = 426, DistrictName = "Kiphire", StateId = 18 },
new DistrictModel { DistrictId = 427, DistrictName = "Kohima", StateId = 18 },
new DistrictModel { DistrictId = 428, DistrictName = "Longleng", StateId = 18 },
new DistrictModel { DistrictId = 429, DistrictName = "Mokokchung", StateId = 18 },
new DistrictModel { DistrictId = 430, DistrictName = "Mon", StateId = 18 },
new DistrictModel { DistrictId = 431, DistrictName = "Niuland", StateId = 18 },
new DistrictModel { DistrictId = 432, DistrictName = "Noklak", StateId = 18 },
new DistrictModel { DistrictId = 433, DistrictName = "Peren", StateId = 18 },
new DistrictModel { DistrictId = 434, DistrictName = "Phek", StateId = 18 },
new DistrictModel { DistrictId = 435, DistrictName = "Shamator", StateId = 18 },
new DistrictModel { DistrictId = 436, DistrictName = "Tseminyu", StateId = 18 },
new DistrictModel { DistrictId = 437, DistrictName = "Tuensang", StateId = 18 },
new DistrictModel { DistrictId = 438, DistrictName = "Wokha", StateId = 18 },
new DistrictModel { DistrictId = 439, DistrictName = "Zunheboto", StateId = 18 },

new DistrictModel { DistrictId = 440, DistrictName = "Angul", StateId = 19 },
new DistrictModel { DistrictId = 441, DistrictName = "Balangir", StateId = 19 },
new DistrictModel { DistrictId = 442, DistrictName = "Balasore", StateId = 19 },
new DistrictModel { DistrictId = 443, DistrictName = "Bargarh", StateId = 19 },
new DistrictModel { DistrictId = 444, DistrictName = "Bhadrak", StateId = 19 },
new DistrictModel { DistrictId = 445, DistrictName = "Boudh", StateId = 19 },
new DistrictModel { DistrictId = 446, DistrictName = "Cuttack", StateId = 19 },
new DistrictModel { DistrictId = 447, DistrictName = "Deogarh", StateId = 19 },
new DistrictModel { DistrictId = 448, DistrictName = "Dhenkanal", StateId = 19 },
new DistrictModel { DistrictId = 449, DistrictName = "Gajapati", StateId = 19 },
new DistrictModel { DistrictId = 450, DistrictName = "Ganjam", StateId = 19 },
new DistrictModel { DistrictId = 451, DistrictName = "Jagatsinghpur", StateId = 19 },
new DistrictModel { DistrictId = 452, DistrictName = "Jajpur", StateId = 19 },
new DistrictModel { DistrictId = 453, DistrictName = "Jharsuguda", StateId = 19 },
new DistrictModel { DistrictId = 454, DistrictName = "Kalahandi", StateId = 19 },
new DistrictModel { DistrictId = 455, DistrictName = "Kandhamal", StateId = 19 },
new DistrictModel { DistrictId = 456, DistrictName = "Kendrapara", StateId = 19 },
new DistrictModel { DistrictId = 457, DistrictName = "Kendujhar (Keonjhar)", StateId = 19 },
new DistrictModel { DistrictId = 458, DistrictName = "Khordha", StateId = 19 },
new DistrictModel { DistrictId = 459, DistrictName = "Koraput", StateId = 19 },
new DistrictModel { DistrictId = 460, DistrictName = "Malkangiri", StateId = 19 },
new DistrictModel { DistrictId = 461, DistrictName = "Mayurbhanj", StateId = 19 },
new DistrictModel { DistrictId = 462, DistrictName = "Nabarangpur", StateId = 19 },
new DistrictModel { DistrictId = 463, DistrictName = "Nayagarh", StateId = 19 },
new DistrictModel { DistrictId = 464, DistrictName = "Nuapada", StateId = 19 },
new DistrictModel { DistrictId = 465, DistrictName = "Puri", StateId = 19 },
new DistrictModel { DistrictId = 466, DistrictName = "Rayagada", StateId = 19 },
new DistrictModel { DistrictId = 467, DistrictName = "Sambalpur", StateId = 19 },
new DistrictModel { DistrictId = 468, DistrictName = "Sonepur (Subarnapur)", StateId = 19 },
new DistrictModel { DistrictId = 469, DistrictName = "Sundargarh", StateId = 19 },

new DistrictModel { DistrictId = 470, DistrictName = "Amritsar", StateId = 20 },
new DistrictModel { DistrictId = 471, DistrictName = "Barnala", StateId = 20 },
new DistrictModel { DistrictId = 472, DistrictName = "Bathinda", StateId = 20 },
new DistrictModel { DistrictId = 473, DistrictName = "Faridkot", StateId = 20 },
new DistrictModel { DistrictId = 474, DistrictName = "Fatehgarh Sahib", StateId = 20 },
new DistrictModel { DistrictId = 475, DistrictName = "Fazilka", StateId = 20 },
new DistrictModel { DistrictId = 476, DistrictName = "Ferozepur", StateId = 20 },
new DistrictModel { DistrictId = 477, DistrictName = "Gurdaspur", StateId = 20 },
new DistrictModel { DistrictId = 478, DistrictName = "Hoshiarpur", StateId = 20 },
new DistrictModel { DistrictId = 479, DistrictName = "Jalandhar", StateId = 20 },
new DistrictModel { DistrictId = 480, DistrictName = "Kapurthala", StateId = 20 },
new DistrictModel { DistrictId = 481, DistrictName = "Ludhiana", StateId = 20 },
new DistrictModel { DistrictId = 482, DistrictName = "Malerkotla", StateId = 20 },
new DistrictModel { DistrictId = 483, DistrictName = "Mansa", StateId = 20 },
new DistrictModel { DistrictId = 484, DistrictName = "Moga", StateId = 20 },
new DistrictModel { DistrictId = 485, DistrictName = "Mohali (SAS Nagar)", StateId = 20 },
new DistrictModel { DistrictId = 486, DistrictName = "Muktsar", StateId = 20 },
new DistrictModel { DistrictId = 487, DistrictName = "Pathankot", StateId = 20 },
new DistrictModel { DistrictId = 488, DistrictName = "Patiala", StateId = 20 },
new DistrictModel { DistrictId = 489, DistrictName = "Rupnagar", StateId = 20 },
new DistrictModel { DistrictId = 490, DistrictName = "Sangrur", StateId = 20 },
new DistrictModel { DistrictId = 491, DistrictName = "Shaheed Bhagat Singh Nagar (Nawanshahr)", StateId = 20 },
new DistrictModel { DistrictId = 492, DistrictName = "Sri Muktsar Sahib", StateId = 20 },
new DistrictModel { DistrictId = 493, DistrictName = "Tarn Taran", StateId = 20 },

new DistrictModel { DistrictId = 494, DistrictName = "Ajmer", StateId = 21 },
new DistrictModel { DistrictId = 495, DistrictName = "Alwar", StateId = 21 },
new DistrictModel { DistrictId = 496, DistrictName = "Banswara", StateId = 21 },
new DistrictModel { DistrictId = 497, DistrictName = "Baran", StateId = 21 },
new DistrictModel { DistrictId = 498, DistrictName = "Barmer", StateId = 21 },
new DistrictModel { DistrictId = 499, DistrictName = "Bharatpur", StateId = 21 },
new DistrictModel { DistrictId = 500, DistrictName = "Bhilwara", StateId = 21 },
new DistrictModel { DistrictId = 501, DistrictName = "Bikaner", StateId = 21 },
new DistrictModel { DistrictId = 502, DistrictName = "Bundi", StateId = 21 },
new DistrictModel { DistrictId = 503, DistrictName = "Chittorgarh", StateId = 21 },
new DistrictModel { DistrictId = 504, DistrictName = "Churu", StateId = 21 },
new DistrictModel { DistrictId = 505, DistrictName = "Dausa", StateId = 21 },
new DistrictModel { DistrictId = 506, DistrictName = "Dholpur", StateId = 21 },
new DistrictModel { DistrictId = 507, DistrictName = "Dungarpur", StateId = 21 },
new DistrictModel { DistrictId = 508, DistrictName = "Hanumangarh", StateId = 21 },
new DistrictModel { DistrictId = 509, DistrictName = "Jaipur", StateId = 21 },
new DistrictModel { DistrictId = 510, DistrictName = "Jaisalmer", StateId = 21 },
new DistrictModel { DistrictId = 511, DistrictName = "Jalore", StateId = 21 },
new DistrictModel { DistrictId = 512, DistrictName = "Jhalawar", StateId = 21 },
new DistrictModel { DistrictId = 513, DistrictName = "Jhunjhunu", StateId = 21 },
new DistrictModel { DistrictId = 514, DistrictName = "Jodhpur", StateId = 21 },
new DistrictModel { DistrictId = 515, DistrictName = "Karauli", StateId = 21 },
new DistrictModel { DistrictId = 516, DistrictName = "Kota", StateId = 21 },
new DistrictModel { DistrictId = 517, DistrictName = "Nagaur", StateId = 21 },
new DistrictModel { DistrictId = 518, DistrictName = "Pali", StateId = 21 },
new DistrictModel { DistrictId = 519, DistrictName = "Pratapgarh", StateId = 21 },
new DistrictModel { DistrictId = 520, DistrictName = "Rajsamand", StateId = 21 },
new DistrictModel { DistrictId = 521, DistrictName = "Sawai Madhopur", StateId = 21 },
new DistrictModel { DistrictId = 522, DistrictName = "Sikar", StateId = 21 },
new DistrictModel { DistrictId = 523, DistrictName = "Sirohi", StateId = 21 },
new DistrictModel { DistrictId = 524, DistrictName = "Sri Ganganagar", StateId = 21 },
new DistrictModel { DistrictId = 525, DistrictName = "Tonk", StateId = 21 },
new DistrictModel { DistrictId = 526, DistrictName = "Udaipur", StateId = 21 },
new DistrictModel { DistrictId = 527, DistrictName = "Shahpura", StateId = 21 },
new DistrictModel { DistrictId = 528, DistrictName = "Neem Ka Thana", StateId = 21 },
new DistrictModel { DistrictId = 529, DistrictName = "Phalodi", StateId = 21 },

new DistrictModel { DistrictId = 530, DistrictName = "Gangtok", StateId = 22 },
new DistrictModel { DistrictId = 531, DistrictName = "Gyalshing (West Sikkim)", StateId = 22 },
new DistrictModel { DistrictId = 532, DistrictName = "Mangan (North Sikkim)", StateId = 22 },
new DistrictModel { DistrictId = 533, DistrictName = "Namchi (South Sikkim)", StateId = 22 },
new DistrictModel { DistrictId = 534, DistrictName = "Pakyong", StateId = 22 },
new DistrictModel { DistrictId = 535, DistrictName = "Soreng", StateId = 22 },

new DistrictModel { DistrictId = 536, DistrictName = "Ariyalur", StateId = 23 },
new DistrictModel { DistrictId = 537, DistrictName = "Chengalpattu", StateId = 23 },
new DistrictModel { DistrictId = 538, DistrictName = "Chennai", StateId = 23 },
new DistrictModel { DistrictId = 539, DistrictName = "Coimbatore", StateId = 23 },
new DistrictModel { DistrictId = 540, DistrictName = "Cuddalore", StateId = 23 },
new DistrictModel { DistrictId = 541, DistrictName = "Dharmapuri", StateId = 23 },
new DistrictModel { DistrictId = 542, DistrictName = "Dindigul", StateId = 23 },
new DistrictModel { DistrictId = 543, DistrictName = "Erode", StateId = 23 },
new DistrictModel { DistrictId = 544, DistrictName = "Kallakurichi", StateId = 23 },
new DistrictModel { DistrictId = 545, DistrictName = "Kanchipuram", StateId = 23 },
new DistrictModel { DistrictId = 546, DistrictName = "Kanyakumari", StateId = 23 },
new DistrictModel { DistrictId = 547, DistrictName = "Karur", StateId = 23 },
new DistrictModel { DistrictId = 548, DistrictName = "Krishnagiri", StateId = 23 },
new DistrictModel { DistrictId = 549, DistrictName = "Madurai", StateId = 23 },
new DistrictModel { DistrictId = 550, DistrictName = "Nagapattinam", StateId = 23 },
new DistrictModel { DistrictId = 551, DistrictName = "Namakkal", StateId = 23 },
new DistrictModel { DistrictId = 552, DistrictName = "Nilgiris", StateId = 23 },
new DistrictModel { DistrictId = 553, DistrictName = "Perambalur", StateId = 23 },
new DistrictModel { DistrictId = 554, DistrictName = "Pudukkottai", StateId = 23 },
new DistrictModel { DistrictId = 555, DistrictName = "Ramanathapuram", StateId = 23 },
new DistrictModel { DistrictId = 556, DistrictName = "Ranipet", StateId = 23 },
new DistrictModel { DistrictId = 557, DistrictName = "Salem", StateId = 23 },
new DistrictModel { DistrictId = 558, DistrictName = "Sivaganga", StateId = 23 },
new DistrictModel { DistrictId = 559, DistrictName = "Tenkasi", StateId = 23 },
new DistrictModel { DistrictId = 560, DistrictName = "Thanjavur", StateId = 23 },
new DistrictModel { DistrictId = 561, DistrictName = "Theni", StateId = 23 },
new DistrictModel { DistrictId = 562, DistrictName = "Thoothukudi (Tuticorin)", StateId = 23 },
new DistrictModel { DistrictId = 563, DistrictName = "Tiruchirappalli", StateId = 23 },
new DistrictModel { DistrictId = 564, DistrictName = "Tirunelveli", StateId = 23 },
new DistrictModel { DistrictId = 565, DistrictName = "Tirupathur", StateId = 23 },
new DistrictModel { DistrictId = 566, DistrictName = "Tiruppur", StateId = 23 },
new DistrictModel { DistrictId = 567, DistrictName = "Tiruvallur", StateId = 23 },
new DistrictModel { DistrictId = 568, DistrictName = "Tiruvannamalai", StateId = 23 },
new DistrictModel { DistrictId = 569, DistrictName = "Tiruvarur", StateId = 23 },
new DistrictModel { DistrictId = 570, DistrictName = "Vellore", StateId = 23 },
new DistrictModel { DistrictId = 571, DistrictName = "Viluppuram", StateId = 23 },
new DistrictModel { DistrictId = 572, DistrictName = "Virudhunagar", StateId = 23 },

new DistrictModel { DistrictId = 573, DistrictName = "Adilabad", StateId = 24 },
new DistrictModel { DistrictId = 574, DistrictName = "Bhadradri Kothagudem", StateId = 24 },
new DistrictModel { DistrictId = 575, DistrictName = "Hyderabad", StateId = 24 },
new DistrictModel { DistrictId = 576, DistrictName = "Jagtial", StateId = 24 },
new DistrictModel { DistrictId = 577, DistrictName = "Jangaon", StateId = 24 },
new DistrictModel { DistrictId = 578, DistrictName = "Jayashankar Bhupalpally", StateId = 24 },
new DistrictModel { DistrictId = 579, DistrictName = "Jogulamba Gadwal", StateId = 24 },
new DistrictModel { DistrictId = 580, DistrictName = "Kamareddy", StateId = 24 },
new DistrictModel { DistrictId = 581, DistrictName = "Karimnagar", StateId = 24 },
new DistrictModel { DistrictId = 582, DistrictName = "Khammam", StateId = 24 },
new DistrictModel { DistrictId = 583, DistrictName = "Komaram Bheem Asifabad", StateId = 24 },
new DistrictModel { DistrictId = 584, DistrictName = "Mahabubabad", StateId = 24 },
new DistrictModel { DistrictId = 585, DistrictName = "Mahabubnagar", StateId = 24 },
new DistrictModel { DistrictId = 586, DistrictName = "Mancherial", StateId = 24 },
new DistrictModel { DistrictId = 587, DistrictName = "Medak", StateId = 24 },
new DistrictModel { DistrictId = 588, DistrictName = "Medchal–Malkajgiri", StateId = 24 },
new DistrictModel { DistrictId = 589, DistrictName = "Mulugu", StateId = 24 },
new DistrictModel { DistrictId = 590, DistrictName = "Nagarkurnool", StateId = 24 },
new DistrictModel { DistrictId = 591, DistrictName = "Nalgonda", StateId = 24 },
new DistrictModel { DistrictId = 592, DistrictName = "Narayanpet", StateId = 24 },
new DistrictModel { DistrictId = 593, DistrictName = "Nirmal", StateId = 24 },
new DistrictModel { DistrictId = 594, DistrictName = "Nizamabad", StateId = 24 },
new DistrictModel { DistrictId = 595, DistrictName = "Peddapalli", StateId = 24 },
new DistrictModel { DistrictId = 596, DistrictName = "Rajanna Sircilla", StateId = 24 },
new DistrictModel { DistrictId = 597, DistrictName = "Ranga Reddy", StateId = 24 },
new DistrictModel { DistrictId = 598, DistrictName = "Sangareddy", StateId = 24 },
new DistrictModel { DistrictId = 599, DistrictName = "Siddipet", StateId = 24 },
new DistrictModel { DistrictId = 600, DistrictName = "Suryapet", StateId = 24 },
new DistrictModel { DistrictId = 601, DistrictName = "Vikarabad", StateId = 24 },
new DistrictModel { DistrictId = 602, DistrictName = "Wanaparthy", StateId = 24 },
new DistrictModel { DistrictId = 603, DistrictName = "Warangal", StateId = 24 },
new DistrictModel { DistrictId = 604, DistrictName = "Yadadri Bhuvanagiri", StateId = 24 },

new DistrictModel { DistrictId = 605, DistrictName = "Dhalai", StateId = 25 },
new DistrictModel { DistrictId = 606, DistrictName = "Gomati", StateId = 25 },
new DistrictModel { DistrictId = 607, DistrictName = "Khowai", StateId = 25 },
new DistrictModel { DistrictId = 608, DistrictName = "North Tripura", StateId = 25 },
new DistrictModel { DistrictId = 609, DistrictName = "Sepahijala", StateId = 25 },
new DistrictModel { DistrictId = 610, DistrictName = "South Tripura", StateId = 25 },
new DistrictModel { DistrictId = 611, DistrictName = "Unakoti", StateId = 25 },
new DistrictModel { DistrictId = 612, DistrictName = "West Tripura", StateId = 25 },

new DistrictModel { DistrictId = 613, DistrictName = "Agra", StateId = 26 },
new DistrictModel { DistrictId = 614, DistrictName = "Aligarh", StateId = 26 },
new DistrictModel { DistrictId = 615, DistrictName = "Ambedkar Nagar", StateId = 26 },
new DistrictModel { DistrictId = 616, DistrictName = "Amethi", StateId = 26 },
new DistrictModel { DistrictId = 617, DistrictName = "Amroha", StateId = 26 },
new DistrictModel { DistrictId = 618, DistrictName = "Auraiya", StateId = 26 },
new DistrictModel { DistrictId = 619, DistrictName = "Ayodhya", StateId = 26 },
new DistrictModel { DistrictId = 620, DistrictName = "Azamgarh", StateId = 26 },
new DistrictModel { DistrictId = 621, DistrictName = "Baghpat", StateId = 26 },
new DistrictModel { DistrictId = 622, DistrictName = "Bahraich", StateId = 26 },
new DistrictModel { DistrictId = 623, DistrictName = "Ballia", StateId = 26 },
new DistrictModel { DistrictId = 624, DistrictName = "Balrampur", StateId = 26 },
new DistrictModel { DistrictId = 625, DistrictName = "Banda", StateId = 26 },
new DistrictModel { DistrictId = 626, DistrictName = "Barabanki", StateId = 26 },
new DistrictModel { DistrictId = 627, DistrictName = "Bareilly", StateId = 26 },
new DistrictModel { DistrictId = 628, DistrictName = "Basti", StateId = 26 },
new DistrictModel { DistrictId = 629, DistrictName = "Bhadohi", StateId = 26 },
new DistrictModel { DistrictId = 630, DistrictName = "Bijnor", StateId = 26 },
new DistrictModel { DistrictId = 631, DistrictName = "Budaun", StateId = 26 },
new DistrictModel { DistrictId = 632, DistrictName = "Bulandshahr", StateId = 26 },
new DistrictModel { DistrictId = 633, DistrictName = "Chandauli", StateId = 26 },
new DistrictModel { DistrictId = 634, DistrictName = "Chitrakoot", StateId = 26 },
new DistrictModel { DistrictId = 635, DistrictName = "Deoria", StateId = 26 },
new DistrictModel { DistrictId = 636, DistrictName = "Etah", StateId = 26 },
new DistrictModel { DistrictId = 637, DistrictName = "Etawah", StateId = 26 },
new DistrictModel { DistrictId = 638, DistrictName = "Farrukhabad", StateId = 26 },
new DistrictModel { DistrictId = 639, DistrictName = "Fatehpur", StateId = 26 },
new DistrictModel { DistrictId = 640, DistrictName = "Firozabad", StateId = 26 },
new DistrictModel { DistrictId = 641, DistrictName = "Gautam Buddha Nagar", StateId = 26 },
new DistrictModel { DistrictId = 642, DistrictName = "Ghaziabad", StateId = 26 },
new DistrictModel { DistrictId = 643, DistrictName = "Ghazipur", StateId = 26 },
new DistrictModel { DistrictId = 644, DistrictName = "Gonda", StateId = 26 },
new DistrictModel { DistrictId = 645, DistrictName = "Gorakhpur", StateId = 26 },
new DistrictModel { DistrictId = 646, DistrictName = "Hamirpur", StateId = 26 },
new DistrictModel { DistrictId = 647, DistrictName = "Hapur", StateId = 26 },
new DistrictModel { DistrictId = 648, DistrictName = "Hardoi", StateId = 26 },
new DistrictModel { DistrictId = 649, DistrictName = "Hathras", StateId = 26 },
new DistrictModel { DistrictId = 650, DistrictName = "Jalaun", StateId = 26 },
new DistrictModel { DistrictId = 651, DistrictName = "Jaunpur", StateId = 26 },
new DistrictModel { DistrictId = 652, DistrictName = "Jhansi", StateId = 26 },
new DistrictModel { DistrictId = 653, DistrictName = "Kannauj", StateId = 26 },
new DistrictModel { DistrictId = 654, DistrictName = "Kanpur Dehat", StateId = 26 },
new DistrictModel { DistrictId = 655, DistrictName = "Kanpur Nagar", StateId = 26 },
new DistrictModel { DistrictId = 656, DistrictName = "Kasganj", StateId = 26 },
new DistrictModel { DistrictId = 657, DistrictName = "Kaushambi", StateId = 26 },
new DistrictModel { DistrictId = 658, DistrictName = "Kushinagar", StateId = 26 },
new DistrictModel { DistrictId = 659, DistrictName = "Lakhimpur Kheri", StateId = 26 },
new DistrictModel { DistrictId = 660, DistrictName = "Lalitpur", StateId = 26 },
new DistrictModel { DistrictId = 661, DistrictName = "Lucknow", StateId = 26 },
new DistrictModel { DistrictId = 662, DistrictName = "Maharajganj", StateId = 26 },
new DistrictModel { DistrictId = 663, DistrictName = "Mahoba", StateId = 26 },
new DistrictModel { DistrictId = 664, DistrictName = "Mainpuri", StateId = 26 },
new DistrictModel { DistrictId = 665, DistrictName = "Mathura", StateId = 26 },
new DistrictModel { DistrictId = 666, DistrictName = "Mau", StateId = 26 },
new DistrictModel { DistrictId = 667, DistrictName = "Meerut", StateId = 26 },
new DistrictModel { DistrictId = 668, DistrictName = "Mirzapur", StateId = 26 },
new DistrictModel { DistrictId = 669, DistrictName = "Moradabad", StateId = 26 },
new DistrictModel { DistrictId = 670, DistrictName = "Muzaffarnagar", StateId = 26 },
new DistrictModel { DistrictId = 671, DistrictName = "Pilibhit", StateId = 26 },
new DistrictModel { DistrictId = 672, DistrictName = "Pratapgarh", StateId = 26 },
new DistrictModel { DistrictId = 673, DistrictName = "Prayagraj", StateId = 26 },
new DistrictModel { DistrictId = 674, DistrictName = "Raebareli", StateId = 26 },
new DistrictModel { DistrictId = 675, DistrictName = "Rampur", StateId = 26 },
new DistrictModel { DistrictId = 676, DistrictName = "Saharanpur", StateId = 26 },
new DistrictModel { DistrictId = 677, DistrictName = "Sambhal", StateId = 26 },
new DistrictModel { DistrictId = 678, DistrictName = "Sant Kabir Nagar", StateId = 26 },
new DistrictModel { DistrictId = 679, DistrictName = "Shahjahanpur", StateId = 26 },
new DistrictModel { DistrictId = 680, DistrictName = "Shamli", StateId = 26 },
new DistrictModel { DistrictId = 681, DistrictName = "Shravasti", StateId = 26 },
new DistrictModel { DistrictId = 682, DistrictName = "Siddharthnagar", StateId = 26 },
new DistrictModel { DistrictId = 683, DistrictName = "Sitapur", StateId = 26 },
new DistrictModel { DistrictId = 684, DistrictName = "Sonbhadra", StateId = 26 },
new DistrictModel { DistrictId = 685, DistrictName = "Sultanpur", StateId = 26 },
new DistrictModel { DistrictId = 686, DistrictName = "Unnao", StateId = 26 },
new DistrictModel { DistrictId = 687, DistrictName = "Varanasi", StateId = 26 },

new DistrictModel { DistrictId = 688, DistrictName = "Almora", StateId = 27 },
new DistrictModel { DistrictId = 689, DistrictName = "Bageshwar", StateId = 27 },
new DistrictModel { DistrictId = 690, DistrictName = "Chamoli", StateId = 27 },
new DistrictModel { DistrictId = 691, DistrictName = "Champawat", StateId = 27 },
new DistrictModel { DistrictId = 692, DistrictName = "Dehradun", StateId = 27 },
new DistrictModel { DistrictId = 693, DistrictName = "Haridwar", StateId = 27 },
new DistrictModel { DistrictId = 694, DistrictName = "Nainital", StateId = 27 },
new DistrictModel { DistrictId = 695, DistrictName = "Pauri Garhwal", StateId = 27 },
new DistrictModel { DistrictId = 696, DistrictName = "Pithoragarh", StateId = 27 },
new DistrictModel { DistrictId = 697, DistrictName = "Rudraprayag", StateId = 27 },
new DistrictModel { DistrictId = 698, DistrictName = "Tehri Garhwal", StateId = 27 },
new DistrictModel { DistrictId = 699, DistrictName = "Udham Singh Nagar", StateId = 27 },
new DistrictModel { DistrictId = 700, DistrictName = "Uttarkashi", StateId = 27 },

new DistrictModel { DistrictId = 701, DistrictName = "Alipurduar", StateId = 28 },
new DistrictModel { DistrictId = 702, DistrictName = "Bankura", StateId = 28 },
new DistrictModel { DistrictId = 703, DistrictName = "Birbhum", StateId = 28 },
new DistrictModel { DistrictId = 704, DistrictName = "Cooch Behar", StateId = 28 },
new DistrictModel { DistrictId = 705, DistrictName = "Dakshin Dinajpur", StateId = 28 },
new DistrictModel { DistrictId = 706, DistrictName = "Darjeeling", StateId = 28 },
new DistrictModel { DistrictId = 707, DistrictName = "Hooghly", StateId = 28 },
new DistrictModel { DistrictId = 708, DistrictName = "Howrah", StateId = 28 },
new DistrictModel { DistrictId = 709, DistrictName = "Jalpaiguri", StateId = 28 },
new DistrictModel { DistrictId = 710, DistrictName = "Jhargram", StateId = 28 },
new DistrictModel { DistrictId = 711, DistrictName = "Kalimpong", StateId = 28 },
new DistrictModel { DistrictId = 712, DistrictName = "Kolkata", StateId = 28 },
new DistrictModel { DistrictId = 713, DistrictName = "Malda", StateId = 28 },
new DistrictModel { DistrictId = 714, DistrictName = "Murshidabad", StateId = 28 },
new DistrictModel { DistrictId = 715, DistrictName = "Nadia", StateId = 28 },
new DistrictModel { DistrictId = 716, DistrictName = "North 24 Parganas", StateId = 28 },
new DistrictModel { DistrictId = 717, DistrictName = "Paschim Bardhaman", StateId = 28 },
new DistrictModel { DistrictId = 718, DistrictName = "Paschim Medinipur", StateId = 28 },
new DistrictModel { DistrictId = 719, DistrictName = "Purba Bardhaman", StateId = 28 },
new DistrictModel { DistrictId = 720, DistrictName = "Purba Medinipur", StateId = 28 },
new DistrictModel { DistrictId = 721, DistrictName = "Purulia", StateId = 28 },
new DistrictModel { DistrictId = 722, DistrictName = "South 24 Parganas", StateId = 28 },
new DistrictModel { DistrictId = 723, DistrictName = "Uttar Dinajpur", StateId = 28 },

new DistrictModel { DistrictId = 724, DistrictName = "Nicobar", StateId = 29 },
new DistrictModel { DistrictId = 725, DistrictName = "North and Middle Andaman", StateId = 29 },
new DistrictModel { DistrictId = 726, DistrictName = "South Andaman", StateId = 29 },

new DistrictModel { DistrictId = 727, DistrictName = "Chandigarh", StateId = 30 },

new DistrictModel { DistrictId = 728, DistrictName = "Dadra and Nagar Haveli", StateId = 31 },
new DistrictModel { DistrictId = 729, DistrictName = "Daman", StateId = 31 },
new DistrictModel { DistrictId = 730, DistrictName = "Diu", StateId = 31 },

new DistrictModel { DistrictId = 731, DistrictName = "Central Delhi", StateId = 32 },
new DistrictModel { DistrictId = 732, DistrictName = "East Delhi", StateId = 32 },
new DistrictModel { DistrictId = 733, DistrictName = "New Delhi", StateId = 32 },
new DistrictModel { DistrictId = 734, DistrictName = "North Delhi", StateId = 32 },
new DistrictModel { DistrictId = 735, DistrictName = "North East Delhi", StateId = 32 },
new DistrictModel { DistrictId = 736, DistrictName = "North West Delhi", StateId = 32 },
new DistrictModel { DistrictId = 737, DistrictName = "Shahdara", StateId = 32 },
new DistrictModel { DistrictId = 738, DistrictName = "South Delhi", StateId = 32 },
new DistrictModel { DistrictId = 739, DistrictName = "South East Delhi", StateId = 32 },
new DistrictModel { DistrictId = 740, DistrictName = "South West Delhi", StateId = 32 },
new DistrictModel { DistrictId = 741, DistrictName = "West Delhi", StateId = 32 },

new DistrictModel { DistrictId = 742, DistrictName = "Anantnag", StateId = 33 },
new DistrictModel { DistrictId = 743, DistrictName = "Bandipora", StateId = 33 },
new DistrictModel { DistrictId = 744, DistrictName = "Baramulla", StateId = 33 },
new DistrictModel { DistrictId = 745, DistrictName = "Budgam", StateId = 33 },
new DistrictModel { DistrictId = 746, DistrictName = "Doda", StateId = 33 },
new DistrictModel { DistrictId = 747, DistrictName = "Ganderbal", StateId = 33 },
new DistrictModel { DistrictId = 748, DistrictName = "Jammu", StateId = 33 },
new DistrictModel { DistrictId = 749, DistrictName = "Kathua", StateId = 33 },
new DistrictModel { DistrictId = 750, DistrictName = "Kishtwar", StateId = 33 },
new DistrictModel { DistrictId = 751, DistrictName = "Kulgam", StateId = 33 },
new DistrictModel { DistrictId = 752, DistrictName = "Kupwara", StateId = 33 },
new DistrictModel { DistrictId = 753, DistrictName = "Poonch", StateId = 33 },
new DistrictModel { DistrictId = 754, DistrictName = "Pulwama", StateId = 33 },
new DistrictModel { DistrictId = 755, DistrictName = "Rajouri", StateId = 33 },
new DistrictModel { DistrictId = 756, DistrictName = "Ramban", StateId = 33 },
new DistrictModel { DistrictId = 757, DistrictName = "Reasi", StateId = 33 },
new DistrictModel { DistrictId = 758, DistrictName = "Samba", StateId = 33 },
new DistrictModel { DistrictId = 759, DistrictName = "Shopian", StateId = 33 },
new DistrictModel { DistrictId = 760, DistrictName = "Srinagar", StateId = 33 },
new DistrictModel { DistrictId = 761, DistrictName = "Udhampur", StateId = 33 },

new DistrictModel { DistrictId = 762, DistrictName = "Kargil", StateId = 34 },
new DistrictModel { DistrictId = 763, DistrictName = "Leh", StateId = 34 },

new DistrictModel { DistrictId = 764, DistrictName = "Lakshadweep", StateId = 35 },

new DistrictModel { DistrictId = 765, DistrictName = "Karaikal", StateId = 36 },
new DistrictModel { DistrictId = 766, DistrictName = "Mahe", StateId = 36 },
new DistrictModel { DistrictId = 767, DistrictName = "Puducherry", StateId = 36 },
new DistrictModel { DistrictId = 768, DistrictName = "Yanam", StateId = 36 }

            };
        }

        public List<DistrictModel> GetDistrictsByStateId(int stateId)
        {
            return GetAllDistricts().Where(d => d.StateId == stateId).ToList();
        }
    }
}
